Jenkinsfile.cycle: Use buildkit in build ALL base components stage.

diff --git a/Jenkinsfile.cycle b/Jenkinsfile.cycle
--- a/Jenkinsfile.cycle
+++ b/Jenkinsfile.cycle
@@ -225,12 +225,12 @@ pipeline {
           withEnv(["HOME=${env.WORKSPACE}"]) {
             docker.withRegistry("https://ts-dockerhub.lsst.org/", "nexus3-lsst_jenkins") {
               sh """
-              export DOCKER_BUILDKIT=0
+              export DOCKER_BUILDKIT=1
               for comp in \${CONDA_PACKAGES}; do
-                docker compose --env-file cycle/cycle.env -f cycle/docker-compose.yaml build ${cacheOption} \${comp}
+                docker compose --env-file cycle/cycle.env -f cycle/docker-compose.yaml build ${cacheOption} \${comp} || echo "\${comp} FAILED."
               done
               for comp in \${CONDA_PACKAGES_C}; do
-                docker compose --env-file cycle/cycle.env -f cycle/docker-compose.yaml build ${cacheOption} \${comp}
+                docker compose --env-file cycle/cycle.env -f cycle/docker-compose.yaml build ${cacheOption} \${comp} || echo "\${comp} FAILED."
               done
               """
               }
