develop-env: Switch to almalinux 9.

diff --git a/build/develop-env/salobj/Dockerfile b/build/develop-env/salobj/Dockerfile
--- a/build/develop-env/salobj/Dockerfile
+++ b/build/develop-env/salobj/Dockerfile
@@ -92,16 +92,16 @@ RUN source /home/saluser/.setup_salobj.sh && \
 
 USER root
 RUN source /home/saluser/.setup_salobj.sh && \
-    ${LSST_SAL_PREFIX}/bin/setupSALKafkaBuildEnvironment update
+    ${LSST_SAL_PREFIX}/bin/setupStackBuildEnvironment
 
-RUN source /home/saluser/.setup_salobj.sh && \
-    ${LSST_SAL_PREFIX}/bin/setupSALKafkaBuildEnvironment avro || echo "Failed."
+# RUN source /home/saluser/.setup_salobj.sh && \
+#     ${LSST_SAL_PREFIX}/bin/setupSALKafkaBuildEnvironment avro || echo "Failed."
 
-RUN source /home/saluser/.setup_salobj.sh && \
-    ${LSST_SAL_PREFIX}/bin/setupSALKafkaBuildEnvironment librdkafka || echo "Failed."
+# RUN source /home/saluser/.setup_salobj.sh && \
+#     ${LSST_SAL_PREFIX}/bin/setupSALKafkaBuildEnvironment librdkafka || echo "Failed."
 
-RUN source /home/saluser/.setup_salobj.sh && \
-    ${LSST_SAL_PREFIX}/bin/setupSALKafkaBuildEnvironment libserdes || echo "Failed."
+# RUN source /home/saluser/.setup_salobj.sh && \
+#     ${LSST_SAL_PREFIX}/bin/setupSALKafkaBuildEnvironment libserdes || echo "Failed."
 
 USER saluser
 
