DELETE ME: M1M3 MAKE DRY RUN

diff --git a/build/mtm1m3_sim/Dockerfile b/build/mtm1m3_sim/Dockerfile
--- a/build/mtm1m3_sim/Dockerfile
+++ b/build/mtm1m3_sim/Dockerfile
@@ -10,7 +10,7 @@ USER root
 RUN dnf install -y dnf-plugins-core epel-release && \
     dnf config-manager --set-enabled powertools && \
     dnf -y --enablerepo=extras install make \
-    gcc-toolset-10 \
+    gcc-toolset-11 \
     git \
     catch-devel \
     boost1.78 \
@@ -43,7 +43,7 @@ RUN git clone https://github.com/lsst-ts/ts_m1m3support && \
 WORKDIR /home/saluser/ts_cRIOcpp/
 RUN /home/saluser/.checkout_repo.sh ${crio_cpp} && \
     source /home/saluser/.setup_sal_env.sh && \
-    source scl_source enable gcc-toolset-10 && \
+    source scl_source enable gcc-toolset-11 && \
     sed -i 's/boost169/boost1.78/' Makefile.inc && \
     make
 
@@ -51,8 +51,8 @@ WORKDIR /home/saluser/ts_m1m3support/
 
 RUN git checkout davemills/DM-41747 && \
     source /home/saluser/.setup_sal_env.sh && \
-    source scl_source enable gcc-toolset-10 && \
-    make SIMULATOR=1 VERBOSE=1 
+    source scl_source enable gcc-toolset-11 && \
+    make SIMULATOR=1 VERBOSE=1 || echo "Compilation failed... Continuing..."
 
 WORKDIR /home/saluser/
 
